### ISSUE TITLE
Crash when click diagnosis

### ISSUE THREAD

**Issue by rockavoldy** [williambj1/GenI2C#10]
crashed when i click diagnosis
i don't know what make this crash, i'm using OpenCore 0.5
have tried with GenI2C 1.2.7 and 1.2.8
my I2C device name is TPDE, ELAN0501, with APIC Pin 0x52
this is the crash_log

[crash_log geni2c.log](https://github.com/williambj1/GenI2C/files/3611832/crash_log.geni2c.log)

**Comment by williambj1** [comment]
Merged into #4 
Thanks for your report.
