### ISSUE TITLE
It is possible to adapt to OpenCore?

### ISSUE THREAD

**Issue by johnnync13** [williambj1/GenI2C#12]
Now, this fixes is to Clover. 
But in OpenCore not exist TgtBridge.
It is possible this project to do a solution to OpenCore builds?

**Comment by williambj1** [comment]
Sure, and I have thought about this for a long time....

**BUT, unfortunately, I have no time recently.**

I'm planning to implement `count`, `skip` support as a workaround first.
Then I will probably implement a method of faking ACPI devices as the OC-Little Guide suggests. But this method requires more skills in ACPI patching since GenI2C probably won't be able to handle tons of External References in ACPI.

**Comment by johnnync13** [comment]
oh! thanks!

**Comment by williambj1** [comment]
Merged into #5

**Comment by alikazemkhanloo** [comment]
Hi @williambj1 ,
can you share your information `skip & count` method? I used trial and error to find the correct number for `skip` renaming `_CRS`.
I searched in my dsdt it was 32nd in search results, But the correct skip value was 33 ( 34th result)

actually I have to search `(_CRS` to find only definitions.

**Comment by alikazemkhanloo** [comment]
looks like I have to search in binary file :| and count right after I reached the TPD0 device :/

**Comment by williambj1** [comment]
You could extend the length of find and replace bytes to make it unique

**Comment by alikazemkhanloo** [comment]
If I find the exact location of it, I would use the skip method. this will be cleaner. but I don't think there is a simple programming way to find the value for the skip.

**Comment by williambj1** [comment]
Maybe you could load the whole table into an array and get the line number range of the trackpad device, then search for every “find item” until it falls into that range?

**Comment by alikazemkhanloo** [comment]
While compiling DSDT.dsl with `-l` flag, It will generate a .lst file. This file contains the byte code for all parts of the `dsl` file. In this file we can find `Device (TPD0)` (or whatever its name is,) to obtain the byte code of it. then you can count all occurrences of `_CRS` before this byte code to get the precise value for the `skip`.

**Comment by alikazemkhanloo** [comment]
using `-l` flag we don't even need to count, we can extend the find and replace to make them unique :| .
