### ISSUE TITLE
Fix Error

### ISSUE THREAD

**Issue by johnnync13** [williambj1/GenI2C#14]
I want to comment you that some laptops not have the trackpad in DSDT. For example, Xiaomi Mi Air. The trackpad is on SSDT-0-XMCC1703.  If you can fix this too... 
![Captura de pantalla 2020-02-03 a las 16 54 26](https://user-images.githubusercontent.com/22727137/73668219-d7a9d080-46a5-11ea-9301-c31f9cb7c616.png)

[I2C-PATCH-I2C1.zip](https://github.com/williambj1/GenI2C/files/4148753/I2C-PATCH-I2C1.zip)

**Comment by SaeedHaidar** [comment]
I am also having this problem my laptop is nitro 5 an-517-51 
(TPAD)

**Comment by williambj1** [comment]
@johnnync13 @SaeedHaidar 

https://github.com/williambj1/GenI2C/wiki/Manually-fix-missing-External-References-within-SSDT-En

Read the wiki above. This is not an ERROR, fix it yourself. GenI2C can't handle this.

**Comment by SaeedHaidar** [comment]
Thanks a lot I will do and tell you my result within an hour
Thanks
