### ISSUE TITLE
ACPI error upon booting

### ISSUE THREAD

**Issue by SaeedHaidar** [williambj1/GenI2C#15]
i do not know if i am supposed to post this here but yeah

when i add the ssdt patch nothing happen 

but when i put the ssdt and patch for clover  i  get acpi error upon booting and my laptop reboot

[I2C-PATCH.zip](https://github.com/williambj1/GenI2C/files/4306754/I2C-PATCH.zip)
[DSDT.zip](https://github.com/williambj1/GenI2C/files/4306755/DSDT.zip)

![Screenshot 2020-03-09 at 13 50 24](https://user-images.githubusercontent.com/25493014/76216509-00773580-6211-11ea-89d2-9cc32d378183.png)
i followed wiki to add the missing obj ..

**Comment by williambj1** [comment]
Did you use ACPI renames properly?

Please attach detailed info about ACPI Errors. You can get them by Hackintool, go to Logs, system, click refresh, then press command +f to search ACPI Error

**Comment by SaeedHaidar** [comment]
my device can not boot with the patches i log in to windows and delete them can i extract the log after i reboot again with hackintool ?

**Comment by SaeedHaidar** [comment]
sorry but i am going to sleep i can not stay wake anymore it has been a long night after i wake up i will send you the log 
have a nice day

**Comment by williambj1** [comment]
> my device can not boot with the patches i log in to windows and delete them can i extract the log after i reboot again with hackintool ?

I'm not positive whether that will work, sometimes logs won't save if the system didn't boot, clover itself has a lot of handy features to disable patches temporary, much more convenient than windows.

I'm going to sleep now as well, I'll check your files tomorrow.

**Comment by SaeedHaidar** [comment]
[config.plist.zip](https://github.com/williambj1/GenI2C/files/4309598/config.plist.zip)
when i disable _OSM and delete this from acpi patch 
[SSDT-XOSI.aml.zip](https://github.com/williambj1/GenI2C/files/4309599/SSDT-XOSI.aml.zip)
my os will boot but touchpad still not working  
also when i open geni2c i get only this info 
[Screenshot 2020-03-10 at 01.32.04.zip](https://github.com/williambj1/GenI2C/files/4309601/Screenshot.2020-03-10.at.01.32.04.zip)

**Comment by SaeedHaidar** [comment]
so the patch was not the problem there something with _OSM

**Comment by williambj1** [comment]
What do you mean "with `_OSM`"? Are you referring to `_OSI`???

I checked your files, the patch is well generated and I don't see any issue.

Also, don't use the gitter room for any support if you are using generated patches here. The developers have no responsibility, warn others as well. **If you need help there, follow the instructions in VoodooI2C official documentation.**

**Comment by SaeedHaidar** [comment]
okay 
sorry i mean 
_OSI yeah

**Comment by williambj1** [comment]
`_OSI` is a dirty hack, It may also lead to different behaviors in other devices, and that's probably why it causes issues for you.

I'm not positive whether this patch still fits for you. There is a much cleaner alternative solution, but it requires much more skills in ACPI and basic programming. Here is the link if you are interested.

https://github.com/daliansky/OC-little/tree/master/20-I2C%E4%B8%93%E7%94%A8%E9%83%A8%E4%BB%B6

The original text is in Chinese. I've checked the contents after Google translate and it's ok to understand

**Comment by SaeedHaidar** [comment]
okay i will check it thanks a lot 
should i close this now

**Comment by williambj1** [comment]
Feel free to reopen if you have more questions. Good luck!
