### ISSUE TITLE
[Suggestion] show more GPIO pins

### ISSUE THREAD

**Issue by dreamwhite** [williambj1/GenI2C#16]
As per issue title, is there any way to get all the pins through GenI2C app? Sometimes it can occur that the default pin doesn't work. At the moment I've realized a small python script, which is currently a WIP, but hope I'll publish it asap. Does GenI2C do this natively without invoking another script? Thanks

**Comment by williambj1** [comment]
@dreamwhite 

Other possible GPIO Pins are listed as comments in the dsl file, probably I should document it.
From my and ben9923's experience, the smaller the pin, the likelier it would work, that's why I chose the first pin as default.

**Comment by dreamwhite** [comment]
Well, I've tested this feature, but it's not working as expected. 
![image](https://user-images.githubusercontent.com/17933708/78531978-bfaa1680-77e6-11ea-8c4f-8f89a9c9e828.png)
Also it can occur sometimes that the GPIO-pin isn't valid (such as the depicted one for example). 

From my script I've calculated the DEC pins (still a WIP, it has less than 2 hours of coding 😃 ) 
![image](https://user-images.githubusercontent.com/17933708/78532145-00a22b00-77e7-11ea-82dc-08db9d1ad8d8.png)

`27` needs to be converted to `0x1B`. I'm using the lists that are linked inside [VoodooI2C GPIO Pinning guide](https://voodooi2c.github.io/#GPIO%20Pinning/GPIO%20Pinning) step 2d

**Comment by dreamwhite** [comment]
Also I've noticed that generating the patch for my DSDT.aml with GenI2C can't make the trackpad work. I attach the DSDT.aml and the patch folder generated by GenI2C:

[DSDT.aml.zip](https://github.com/williambj1/GenI2C/files/4436461/DSDT.aml.zip)

[I2C-PATCH.zip](https://github.com/williambj1/GenI2C/files/4436467/I2C-PATCH.zip)

What changes between my patch, manually done with MaciASL, and the GenI2C patch is that my `TPD0` device is well-pinned as it  `Return (ConcatenateResTemplate (SBFB, SBFI))`. GenI2C changes the `SBFI` with `SBFG`.

Below my `TPD0._CRS` without GenI2C patch
![My Custom DSDT.aml](https://user-images.githubusercontent.com/17933708/78532624-dd2bb000-77e7-11ea-99a6-7527f1db948c.png)

and below my `TPD0._CRS` with GenI2C patch

![image](https://user-images.githubusercontent.com/17933708/78532858-3b589300-77e8-11ea-807f-405353bf5fdb.png)

Below my PCI devices list: `I2C0` PCI address is `pci8086,9d60`
![image](https://user-images.githubusercontent.com/17933708/78532904-4ad7dc00-77e8-11ea-8e4f-1b1eda078722.png)

**Comment by williambj1** [comment]
@dreamwhite 

> Well, I've tested this feature, but it's not working as expected.

I don't understand this, could you please describe further rather than saying "not working as expected"?

> such as the depicted one for example

This should never happen, if the pin is invalid, it's the manufacturer's fault, APIC pins should always have a valid GPIO pin.

> From my script I've calculated the DEC pins

I used to hardcode the pins before and found this was actually stupid, the pins maps are, in fact, several linear functions, See code below.

https://github.com/williambj1/GenI2C/blob/74278f2bb6737d2334a73e884c7c4716a3d53129/GenI2C/APIC2GPIO.swift#L13-L57

You could recalculate the pins and verify them yourself, I'm sure there's no mistake here. I calculated all the pins on a scratch paper before I wrote this function.

> What changes between my patch, manually done with MaciASL, and the GenI2C patch is that my TPD0 device is well-pinned as it Return (ConcatenateResTemplate (SBFB, SBFI)). GenI2C changes the SBFI with SBFG.

Believe me or not, that's really all you need :) I'll take a look at your files later.

**Comment by dreamwhite** [comment]
Wow, very nice. I'll reply to your questions:

> I don't understand this, could you please describe further rather than saying "not working as expected"?
Yeah, sorry. I was intending that trackpad stops working if changing from `SBFI` to `SBFG`. That's the only difference you can find inside the attached files.

> You could recalculate the pins and verify them yourself, I'm sure there's no mistake here. I calculated all the pins on a scratch paper before I wrote this function.
Well I've created a "dictionary" in Python (a C/C++ struct equivalent) which maps `GPP_IRQ` with the corresponding HEX pin. When I'll publish the tool I'll surely link it inside this issue 😄

**Comment by Mateo1234454545** [comment]
> What changes between my patch, manually done with MaciASL, and the GenI2C patch is that my `TPD0` device is well-pinned as it `Return (ConcatenateResTemplate (SBFB, SBFI))`. GenI2C changes the `SBFI` with `SBFG`.

That happens to me too , on a Dell 5570.
After that change touchpad doesn't work.

**Comment by williambj1** [comment]
Thank you for your interest, closed as it's not a bug report and the questions are all answered.
