### ISSUE TITLE
Needs new algorithm for i2c Dell0767 trackpad and analogs

### ISSUE THREAD

**Issue by truepatch** [williambj1/GenI2C#18]
[DSDT-clean.dsl.zip](https://github.com/williambj1/GenI2C/files/4465200/DSDT-clean.dsl.zip)
1. GenI2C -> DSDT-clean -> TPD0. [I2C-PATCH-TPD0-GPIO.zip](https://github.com/williambj1/GenI2C/files/4465208/I2C-PATCH-TPD0-GPIO.zip)

2. GenI2C -> DSDT-clean -> TPL1. [I2C-PATCH-TPL1-GPIO.zip](https://github.com/williambj1/GenI2C/files/4465209/I2C-PATCH-TPL1-GPIO.zip)

3. Add Clover boot patch GPI0, TPD0, TPL1.

Result - work in polling mode. GPIO not work. Errors:
SSCN not implemented in ACPI tables
FMCN not implemented in ACPI tables
Incompatible APIC interrupt pin (0x33 > 0x2f) and no GPIO interrupts found; 

Next, I changed the following settings.
1. Move SSCN, FMCN.  
_SB.PCI0.I2C0.TPD0 -> _SB.PCI0.I2C0
_SB.PCI0.I2C1.TPL1 -> _SB.PCI0.I2C1
2.  

```
Scope (\_SB.PCI0.I2C0.TPD0)
    {
        Method (_CRS, 0, NotSerialized)  // _CRS: Current Resource Settings
        {
            ......
            Return (ConcatenateResTemplate (\_SB.PCI0.I2C0.TPD0.SBFB, \_SB.PCI0.I2C0.TPD0.SBF**I**))
            // generator bug, need in this place SBFG
        }
    }
```

3.

  ```
  Scope (\_SB.PCI0.I2C1.TPL1)
    {
        Method (_CRS, 0, NotSerialized)  // _CRS: Current Resource Settings
        {
            ......
            Return (ConcatenateResTemplate (\_SB.PCI0.I2C1.TPL1.SBFB, \_SB.PCI0.I2C1.TPL1.SBF**G**))
            // generator bug, need in this place SBFI
        }
    }
```

I lost 3 days to find this problem 😓

🔥 patch _OSI  to XOSI enabled. "Windows 2013" and height. [SSDT-XOSI.aml.zip](https://github.com/williambj1/GenI2C/files/4465333/SSDT-XOSI.aml.zip)
**OR**
🔥 patch _OSI  to XOSI enabled [SSDT-OC-XOSI.aml.zip](https://github.com/williambj1/GenI2C/files/4465838/SSDT-OC-XOSI.aml.zip) + OSID to XSID enabled [SSDT-OC-DELL.aml.zip](https://github.com/williambj1/GenI2C/files/4465839/SSDT-OC-DELL.aml.zip)
 

 ----------------------------------------------------------------------------

🎉 👉 [SSDT-I2C-DELL-WORK.zip](https://github.com/williambj1/GenI2C/files/4465263/SSDT-I2C-DELL-WORK.zip) 🔬[DELL0767.ioreg.zip](https://github.com/williambj1/GenI2C/files/4465294/DELL0767.ioreg.zip)

Add EFI/CLOVER/kexts/Other/ 
VoodooI2C.kext
VoodooI2CHID.kext
VoodooPS2Controller.kext
 
Trackpad detected 5 touch, worked right side gestures for notification panel, no freezing.
     
![2020-04-11_23-36-45](https://user-images.githubusercontent.com/3313882/79053123-4ed68480-7c54-11ea-9d91-dce8713a59cd.png)

**Comment by lersy** [comment]
hey dude 

I have also same problem. I cannot make my touchpad work in GPIO interrupt mode whatever I tried. I downloaded the files you uploaded but did not understand them. I am uploading mine. Can you check it for me? what am I missing? I also have a dell laptop. Can you fix my errors ?

@truepatch 

[lersy-nogpio.zip](https://github.com/williambj1/GenI2C/files/4533865/lersy-nogpio.zip)

**Comment by truepatch** [comment]
@lersy add patched DSDT.aml in TPD0, needs change method Interrupt and Pin list
```
            Name (SBFI, ResourceTemplate ()
            {
                Interrupt (ResourceConsumer, Level, ActiveLow, ExclusiveAndWake, ,, _Y25)
                {
                    0x00000021,
                }
            })
            Name (SBFG, ResourceTemplate ()
            {
                GpioInt (Level, ActiveLow, ExclusiveAndWake, PullDefault, 0x0000,
                    "\\_SB.PCI0.GPI0", 0x00, ResourceConsumer, ,
                    )
                    {   // Pin list
                        0x001B
                    }
            })
```
[SSDT-I2C.zip](https://github.com/williambj1/GenI2C/files/4536632/SSDT-I2C.zip)
Try use (method rename parameters in the patch file)
SSDT-GPI0.aml, SSDT-I2C-SPED.aml + **SSDT-TPD0.aml**  
OR
SSDT-GPI0.aml, SSDT-I2C-SPED.aml + **SSDT-TPD1.aml**

**Comment by lersy** [comment]
thanks for help @truepatch 

I will use the pair SSDT-XOSI, SSDT-GPIO, SSDT-I2C-SPED + SSDT-TPD1. you provided. I assume you made the necessary changes. Can you help me about config.plist renames? Output gives me a text but it includes Targetbridge which is not covered by Opencore. 

Thanks in advance dude. I have been dealing with this for a long time.

[config-rename.zip](https://github.com/williambj1/GenI2C/files/4536686/config-rename.zip)

**Comment by truepatch** [comment]
I myself don’t know how to use Target Bridge in opencore.
But I think you just need to add the name of the device.
As an [example](https://www.insanelymac.com/forum/topic/338516-opencore-discussion/?page=126)

**Comment by lersy** [comment]
Mate I added rename patches as in screenshoot and now it says nothing. 
![Screen Shot 2020-04-27 at 02 46 29](https://user-images.githubusercontent.com/44593726/80323055-ac142d80-8831-11ea-815d-6c882518cd67.png)
![Screen Shot 2020-04-27 at 02 47 40](https://user-images.githubusercontent.com/44593726/80323058-adddf100-8831-11ea-8c14-0fcbdcb283b6.png)

**Comment by truepatch** [comment]
You need to use renaming correctly, it’s better to try first with Clover to start all the equipment, and then the OC.

**Comment by williambj1** [comment]
Closed as it originally a user mistake, good to know it's fixed :P
