### ISSUE TITLE
v1.3.1 Application crashes after generate attempt

### ISSUE THREAD

**Issue by hrytskivr** [williambj1/GenI2C#21]
10.15.4
After selecting DSDT and proceeding (generate for this computer selected) it just crashes.

**Comment by williambj1** [comment]
@hrytskivr Please post your DSDT and some basic info about your device (CPU, etc)

**Comment by hrytskivr** [comment]
[DSDT.dsl.zip](https://github.com/williambj1/GenI2C/files/4581382/DSDT.dsl.zip)

**Comment by hrytskivr** [comment]
Razer Blade Advanced 15" 2018
i7 8750H
UHD630

**Comment by hrytskivr** [comment]
I've managed to hot-patch everything on my own, but if you need debug info I can provide.
