### ISSUE TITLE
Suggestion 

### ISSUE THREAD

**Issue by johnnync13** [williambj1/GenI2C#3]
It would be great if in the SSDT you put the objects you use
![capture](https://user-images.githubusercontent.com/22727137/58826579-4b8c6880-8641-11e9-9040-1100161beede.png)

**Comment by williambj1** [comment]
Thanks for your feedback!
I'm not sure how to External an object that is created by `CreateDWordField`. And I'm still doing some research. 

### Try this:
[SSDT-TPD0.dsl.zip](https://github.com/williambj1/GenI2C/files/3250444/SSDT-TPD0.dsl.zip)

**Comment by williambj1** [comment]
Don't forget to Rename `USTP` to `XSTP`
I'm sorry that I forgot to integrate it into the program.

**Comment by johnnync13** [comment]
The truth is that the tool is great, if it exceeds hardware level programming it could help make the transition to macOS but I'm in the third race and I do not have time. @williambj1

**Comment by williambj1** [comment]
@DogAndPot has done over 90% of the translation work. 
I don't know much about coding so it might be impossible for me to do  **Hardware level programming**.
Perhaps the only thing possible for me to do right now is to treat the dsdt file as text and generate an SSDT by extracting data.

Right now, I have no idea how to External objects created by `CreateDWordField` & `CreateWordField`. According to my experience, these objects in `_CRS` can be changed to SBFB and they function equally. However, as Ben Raz suggested, it's better to use the original ones (with more information returned) instead.

**Comment by johnnync13** [comment]
I add dsdt origin files like you say on gitter
[dsl.zip](https://github.com/williambj1/GenI2C/files/3253067/dsl.zip)

**Comment by williambj1** [comment]
Hi! @johnnync13 

I tried to fix this issue and please check the latest release and tell me whether it works or not!

Thanks!

**Comment by johnnync13** [comment]
@williambj1  Oh thanks! Works fine! 
I also have another suggestion for improvement, to complete the tool. It would be nice if the output of the application, it would appear that Kext use of VoodooI2C, I do not know if this would be possible

**Comment by johnnync13** [comment]
I have this error 
![Captura de pantalla 2019-06-06 a las 11 20 07](https://user-images.githubusercontent.com/22727137/59021948-1e140a80-884d-11e9-9dde-359a7d07cd1e.png)

**Comment by DogAndPot** [comment]
Hi, @johnnync13 
GenI2C for Mac is almost done！Now it is still in beta, with unknown bugs.
Would you please to help me test it.

**Comment by johnnync13** [comment]
@DogAndPot yeah of course!

**Comment by DogAndPot** [comment]
@johnnync13 
[GenI2C.zip](https://github.com/williambj1/GenI2C/files/3309967/GenI2C.zip)

This is the latest version.I add DSDT disassembler and maclog.

**Comment by johnnync13** [comment]
Works on 10.13.x and 10.14 on xiaomi gaming, xiaomi pro, xiaomi mi air, xiaomi notebook air. Great job!

**Comment by DogAndPot** [comment]
Is the information on the first page right?Or does the hotpatch work?

**Comment by johnnync13** [comment]
the info is correct and hotpatch works perfectly! Only not works for example with xiaomi mi air, because the tpd0 is on SSDT-0

**Comment by johnnync13** [comment]
[Xiaomi-Mi-Air-2018.zip](https://github.com/williambj1/GenI2C/files/3356995/Xiaomi-Mi-Air-2018.zip)

[I2C-PATCH.zip](https://github.com/williambj1/GenI2C/files/3356996/I2C-PATCH.zip)
Not correct fix... I have some errors @williambj1 @DogAndPot 
The correct device is on ssdt-0, I2C1-TPD0

**Comment by williambj1** [comment]
@johnnync13 Thanks for your report!

I checked your files and those errors are actually acceptable.

Unlike iasl, GenI2C can't really "understand" the ACPI tables, it can only do basic text modification to achieve SSDT generation. So it's very common to have missing external references. Some "Objects" are hidden in lines that contain "Store" or something and these lines are usually too complicated to determine the "Objects'" type and its' location in the line. So I wrote a guide to teach people how to manually solve this. [Link](https://github.com/williambj1/GenI2C/wiki/Manually-fix-missing-External-References-within-SSDT-En)

In your generated SSDT, there's a missing `External(_SB.PCI0.I2C1.TPD0.SBFS, UnknownObj)`, this is a bug of GenI2C and I've confirmed it. This issue will be solved soon.

> @williambj1 Oh thanks! Works fine!
> I also have another suggestion for improvement, to complete the tool. It would be nice if the output of the application, it would appear that Kext use of VoodooI2C, I do not know if this would be possible

To be honest, this feature seems to be amazing but unfortunately, it's impossible. Kexts may not have the ability to patch DSDT/SSDT directly, I don't know much about and it's certainly out of my scope, perhaps other professional programmers will have some ideas.

All in all, thanks for supporting GenI2C, testing it and reporting bugs😊.

**Comment by johnnync13** [comment]
@williambj1 It would be great if the output was also generated with config.plist as Hackintool, both for clover and OpenCore

**Comment by johnnync13** [comment]
@williambj1 I suppose that you know that there are some examples to fix trackpad on OC. 
https://github.com/daliansky/OC-little/tree/master/20-I2C专用部件
I will try to do on my laptop because, the problem is with XOSI can't boot in windows

**Comment by williambj1** [comment]
Yes, I know those methods, and it's highly recommended to use them. It's quite hard to make automated patches based on this model, I tried and had a hard time implementing the "Presetting variables" part of the patch.

**Comment by kecinzer** [comment]
I try to switch from interrupt to polling mode. I have generated SSDT file, but as I can see I also need replacement in config.plist.
But I use OpenCore that dont have TgtBridge. Is there any way how to solve this?

**Comment by williambj1** [comment]
It can't be achieved automatically right now but you can extend the find and replace to make it unique.
I have no idea why you decided to switch to a worse mode. You could follow the instructions in the link given by johnnync13 as an alternative solution.

**Comment by kecinzer** [comment]
And how can I extend it?
Switch to worse mode? Because I get advise from creators that Polling mode is enhanced in version 2.4.

**Comment by johnnync13** [comment]
@williambj1 I change the aml and now the trackpad not works in open core... but I think that the fixes are well.
[Archive.zip](https://github.com/williambj1/GenI2C/files/4452594/Archive.zip)

**Comment by johnnync13** [comment]
@williambj1 the problem is resolved. Now is fixed like daliansky
