### ISSUE TITLE
Mode not detected

### ISSUE THREAD

**Issue by Mateo1234454545** [williambj1/GenI2C#9]
Geni2c doesn't detect the mode of my trackpad.
Attaching clover folder , if needed.
[Screenshot.pdf](https://github.com/williambj1/GenI2C/files/3434544/Screenshot.pdf)
[CLOVER.zip](https://github.com/williambj1/GenI2C/files/3434545/CLOVER.zip)

**Comment by williambj1** [comment]
@Mateo1234454545 
This is a known issue but unfortunately, I don't have time to fix it recently.
It'll be great if you can submit a PR and fix it.
Listed to [`Known bugs`](https://github.com/williambj1/GenI2C/issues/4#issue-458681210)

Thanks for pointing out this issue!
